name: Run Python

on: [push]  # 每次推送代码时自动运行

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 运行脚本
        run: python XMAPort.py
